workflow:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "develop")
      when: always
    - when: never
   
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - release

build-job:   
  environment: development    # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building the image ..."
    - docker build --build-arg NODE_ENV=development -t discount:v1.$CI_PIPELINE_IID -t discount:latest .
    - echo "Building complete."  
  tags:
    - internal
    - shared

deploy-job:
        # This job runs in the deploy stage.
  stage: deploy  # It only runs when job in build-job stage completes successfully.
  environment: development
  script:
    - echo "Deploying application..."
    - sudo docker compose -f /app/discount/backend/docker-compose.yml up -d 
    - sudo docker exec -i discount php artisan migrate
    - echo "Application successfully deployed."
  needs: 
    - build-job
  tags:
    - internal
    - shared
  
release-job:
  # This job runs in the release stage which does the release.
  environment: development
  stage: release
  script:
    - echo "Create release ..."
  release:
    description: "This release was made from commit $CI_COMMIT_SHORT_SHA"
    name: 'Discount v1.$CI_PIPELINE_IID'
    tag_name: 'v1.$CI_PIPELINE_IID'
  needs:
    - deploy-job
  tags:
    - internal
    - shared

  


    


  
  


  
