workflow:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && ($CI_COMMIT_BRANCH == "develop")
      when: always
    - when: never
   
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - release

include:
  - template: Security/SAST.gitlab-ci.yml

.tags-docker: &docker
  - docker
  - shared

.tags-global: &tags
  - internal
  - shared

.rules-push: &push
   - if: $CI_PIPELINE_SOURCE == "push"

build-job:   
  environment: development    # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building the image ..."
    - mc cp discount/discount/backend/.env /app/discount/backend/env/
    - docker build --build-arg NODE_ENV=development -t discount:v1.$CI_PIPELINE_IID -t discount:latest .
    - echo "Building complete."  
  tags:
    *tags
  rules:
    *push

sast:
  stage: test
  tags:
    *docker

deploy-job:
        # This job runs in the deploy stage.
  stage: deploy  # It only runs when job in build-job stage completes successfully.
  environment: development
  script:
    - echo "Deploying application..."
    - docker compose -f /app/discount/backend/docker-compose.yml up -d 
    - docker exec -i discount php artisan migrate
    - echo "Application successfully deployed."
  needs: 
    - build-job
  tags:
    *tags
  rules:
    *push

seed-job:
        # This job runs in the deploy stage.
  stage: deploy  # It only runs when you click on Run Pipeline.
  environment: development
  script:
    - echo "Seeding the database..."
    - docker exec -i discount php artisan db:seed
    - echo "PHP successfully seeded the database."
  tags:
    *tags
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  
release-job:
  # This job runs in the release stage which does the release.
  environment: development
  stage: release
  script:
    - echo "Create release ..."
  release:
    description: "This release was made from commit $CI_COMMIT_SHORT_SHA"
    name: 'Discount v1.$CI_PIPELINE_IID'
    tag_name: 'v1.$CI_PIPELINE_IID'
  needs:
    - deploy-job
  tags:
    *tags
  rules:
    *push
  


    


  
  


  
