version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d/discount.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html/"
      - "./logs/nginx.log:/var/log/nginx/"
    container_name: discount_nginx
    hostname: discount_nginx
    restart: unless-stopped
    networks:
      - lemp_stack
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      php:
        condition: service_started 

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: discount:latest
    env_file:
      - ./env/.env
    container_name: discount
    hostname: discount
    restart: unless-stopped
    environment:
      SERVICE_NAME: discount
      SERVICE_TAGS: dev
    networks:
      - lemp_stack
    volumes:
      - "./php/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      mysql:
        condition: service_healthy 

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
       - '3306:3306'
    container_name: discount_mysql
    hostname: discount_mysql
    restart: unless-stopped
    environment:
       MYSQL_ROOT_PASSWORD: 'password'
       MYSQL_DATABASE: 'laravel'
       MYSQL_USER: 'discount'
       MYSQL_PASSWORD: 'password'
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
       SERVICE_TAGS: dev
       SERVICE_NAME: mysql
    volumes:
        - './mysql/data/:/var/lib/mysql/'
    networks: 
      - lemp_stack
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p password'
      retries: 3
      timeout: 5s

networks:
  lemp_stack:
volumes:
  data:
  logs:  
